### ISSUE TITLE
liquidPledgingBase.sol Name Changes

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/liquidpledging#11]
pm = cm (after the change to campaign)

transfer = transferPledge (transfer is a solidity common name, not easy to read or audit) this is global name change and a tough one to do...

findNote = findOrCreatePledge (why 2 functions with same name? not easy to read or audit)

**Comment by jbaylina** [comment]
transfer is not a reserverd word in solidity, so I keep it. The rest are changed.
