### ISSUE TITLE
Bug when vetoing a delegation

### ISSUE THREAD

**Issue by perissology** [Giveth/liquidpledging#15]
To veto a delegation, I call the the `transfer` method with the delegate as the recipient, thus removing the `proposedProject` from the note.

However when we do this, we call `appendDelegate`, and append the recipient to the delegationChain, even if the recipient is already last in the delegation chain.

Thus with a picky donor who rejects often or whos note has been passed around a lot, it is possible to have `n.delegationChain.length > MAX_DELEGATES` which will throw and the donor will have no way to reject the delegation.

```
function appendDelegate(uint64 idNote, uint amount, uint64 idReceiver) internal  {
        Note storage n= findNote(idNote);

        require(n.delegationChain.length < MAX_DELEGATES); //TODO change to revert and say the error
        uint64[] memory newDelegationChain = new uint64[](n.delegationChain.length + 1);
        for (uint i=0; i<n.delegationChain.length; i++) {
            newDelegationChain[i] = n.delegationChain[i];
        }
...
```

We either need a separate method `rejectProposedProject` or to change `appendDelegate` to not append the `idReceiver` if they are already the last delegate in the chain.

something like...

```
function appendDelegate(uint64 idNote, uint amount, uint64 idReceiver) internal  {
        Note storage n= findNote(idNote);

        if (n.delegationChain[ n.delegationChain.length ] == idReceiver) {
            // the last delegate in the chain is already the idReceiver
            uint64[] memory newDelegationChain = n.delegationChain;
        } else {
            require(n.delegationChain.length < MAX_DELEGATES); //TODO change to revert and say the error
            uint64[] memory newDelegationChain = new uint64[](n.delegationChain.length + 1);
            for (uint i=0; i<n.delegationChain.length; i++) {
                newDelegationChain[i] = n.delegationChain[i];
            }

            // Make the last item in the array the idReceiver
            newDelegationChain[n.delegationChain.length] = idReceiver;
        }

        uint64 toNote = findNote(
                n.owner,
                newDelegationChain,
                0,
                0,
                n.oldNote,
                PaymentState.NotPaid);
        doTransfer(idNote, toNote, amount);
    }
```

**Comment by jbaylina** [comment]
Can you write a test for this case?  I don't really see how this would happen. When you cancel a delegation, the delegationChain is reduced, And when you roll back an intended project, the delegation  chain is maintained or reduced.

**Comment by perissology** [comment]
The https://github.com/Giveth/liquidpledging/tree/veto_delegation_bug branch contains a test case in `tests/VetoDelegation.js`

You'll see in the state printout that the delegationChain is not maintained, but is grown when rolling back the intended project

**Comment by jbaylina** [comment]
Fixed and added the tests in master
