### ISSUE TITLE
each payment must be confirmed by the vault owner

### ISSUE THREAD

**Issue by perissology** [Giveth/liquidpledging#16]
Currently the vault requires the owner to confirm every payment before it can be withdrawn. Is this the vault we intend to deploy? Or do we want to use a vault with a paymentDelay of say 3 days. Where if the vault owner doesn’t cancel the payment, the recipient can withdraw after the time period w/o direct interaction from the vault owner

**Comment by jbaylina** [comment]
In the first version, I expect to be manually, and when stable, just accept automatically without any wait.
