### ISSUE TITLE
possible for plugins to prevent transfer of eth

### ISSUE THREAD

**Issue by perissology** [Giveth/liquidpledging#33]
In the current plugin system, if present, we call the plugins for the pledge owner, all delegates in the chain, and the intendedProject. This presents a few issues.

1. it is possible for any malicious actor to write a plugin that either throws or returns 0 when called and thus makes it impossible to transfer the pledge, essentially causing the eth to become stuck in the pledge for eternity.

2. it is possible for an `intendedProject` to prevent the owner of the pledge from rejecting the delegation. The project plugin can easily detect if they are being rejected by looking for `fromPledge.intendedProject == projectPlugin.idProject && toPledge.owner != projectPlugin.idProject && toPledge.intendedProject != projectPlugin.idProject`

One possible solution is to have a whitelist consisting of a list of approved plugin bytecode hashes. Using assembly, we can verify the bytecode at the provided plugin address in the initial `addProject/Delegate/Giver` call and throw if the provided plugin isn't an approved plugin.

**Comment by jbaylina** [comment]
The thing is that when you send the money to an admin that has a plugin, you assume that you trust that admin. The same way than in ethereum you trust a contract when you are sending eth to it.

Remember that plugins can not be changes! This avoid a lot of vector attacks.

Yes, I like the idea of whitelist the plugins for extra protection
