### ISSUE TITLE
Redundant getter in LiquidPledgingMock

### ISSUE THREAD

**Issue by Quazia** [Giveth/liquidpledging#41]
There's a getter in `LiquidPledgingMock.sol` for mock_time. It seems like this is redundant since it's already public access. This and I would switch mock_time to mixed case. I also think it might make sense to be able to set the block time for the mock in the constructor.

**Comment by perissology** [comment]
the `getTime` function overrides `LiquidPledging.sol` `getTime` and is used in testing to "advance" the blocktime.

What do you mean set the blocktime? are you talking about `mock_time`? What would be the use?

**Comment by Quazia** [comment]
Oh, that makes sense. Yeah, I didn't realize it was overriding. I'm closing this issue but I still think that mock_time should follow mixedcase.
