### ISSUE TITLE
Global Name Changes

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/liquidpledging#9]
I would like to propose many name changes:

Donor = Giver

Project = Campaign

Note = Pledge

NoteManager = PledgeAdmin

Manager = Admin

hNote2ddx = hNote2idx

NotPaid = Pledged

proposedProject = intendedCampaign

**Comment by perissology** [comment]
I would suggest not changing project -> campaign.A Giveth campaign & milestone are both a liquidPledging project.

same goes for proposedProject -> intendedCampaign.

also, NoteManager & Manager I think are the same thing, so they should be consolidated

**Comment by perissology** [comment]
also maybe changing `Paying` state for a note to `InitializedWithdraw` is a bit clearer a the withdraw is a multi-step process (for the foreseeable future).

**Comment by jbaylina** [comment]
I just saw @perissology comments. I already changed the names, but if you want I can move it back.  Please reach a concensus on this between the native speakers..

**Comment by perissology** [comment]
@GriffGreen  and I decided to go back to project. #21

**Comment by jbaylina** [comment]
Ok, merged
